### ISSUE TITLE
 [Server thread/ERROR]: Could not pass event CraftItemEvent to RandomEnchant v1.1]

### ISSUE THREAD

**Issue by AnTiDoTxD** [hyperdefined/RandomEnchant#1]
![GhO1dYArSs2U_7c-me8zuA](https://user-images.githubusercontent.com/37021829/111071482-06b48780-84df-11eb-930f-f71a154b3d3c.png)

**Comment by hyperdefined** [comment]
Delete the `plugins\RandomEnchant` folder and restart your server.

**Comment by AnTiDoTxD** [comment]
I did that, same thing happened.

**Comment by AnTiDoTxD** [comment]
![download](https://user-images.githubusercontent.com/37021829/111076761-5488ba00-84f6-11eb-8551-277c42e7a2c9.png)
I did that, and now I get these two exceptions.

**Comment by hyperdefined** [comment]
This issue is fixed in [1.1.1](https://github.com/hyperdefined/RandomEnchant/releases/tag/1.1.1). Feel free to create anymore issues or reply here if the issue keeps happening.
