### ISSUE TITLE
[16:10:03 ERROR]: Could not pass event CraftItemEvent to RandomEnchant v1.1.1

### ISSUE THREAD

**Issue by AnTiDoTxD** [hyperdefined/RandomEnchant#2]
Sorry to bother you, but the issue occours again. I even deleted the server and re-installed it to get the same result.
![Screenshot_3](https://user-images.githubusercontent.com/37021829/111166722-0e406300-85a9-11eb-9971-0b688bd8dc6a.png)

**Comment by hyperdefined** [comment]
Alright this is even more confusing now. Something is null when it shouldn't be. Can you post your `RandomEnchant/config.yml` file?

**Comment by AnTiDoTxD** [comment]
Sure. It wasn't edited at all, but I put default limits to false because max level range was 10 and it doesn't exist in vanilla. I edited it to .log because Github doesn't let me upload it in another way.
[config.yml.log](https://github.com/hyperdefined/RandomEnchant/files/6143693/config.yml.log)

**Comment by AnTiDoTxD** [comment]
Unfortunately I kinda don't know java language to help you out :))

**Comment by hyperdefined** [comment]
You config looks correct. I asked for your config because the error has something to do with the config it seems. I have not seen this in my own testing.

First, do you have any other plugins installed?

**Comment by AnTiDoTxD** [comment]
I had that plugin to enable the skins from premium players even if offline-mode is set to true, but with the new server, random enchant is the only plugin that I'm running.

**Comment by AnTiDoTxD** [comment]
I have the latest Spigot and Minecraft versions.

**Comment by hyperdefined** [comment]
Delete the current version you have installed, and install this one. https://mega.nz/file/kIB0gbSQ#xzabAmde2KI8RMu_Ewdz6yPxA0utzVRbXhDOIf-Pk-4

It will print some stuff to the server console, so just send me your entire server log.

To just confirm, does this happen on all tools and armor?

**Comment by AnTiDoTxD** [comment]
Yes, it does. I tried to craft all types of tools and armour, all of them with gold.
[2021-03-15-4.log.gz](https://github.com/hyperdefined/RandomEnchant/files/6143964/2021-03-15-4.log.gz)
[latest.log](https://github.com/hyperdefined/RandomEnchant/files/6143965/latest.log)

**Comment by hyperdefined** [comment]
I found the issue finally, it was such a dumb typo but it's finally fixed.

I will release the new version soon! Thank you for the help.

**Comment by AnTiDoTxD** [comment]
No problem my guy, anytime!

**Comment by hyperdefined** [comment]
Version 1,2 has the new fix in it.

https://github.com/hyperdefined/RandomEnchant/releases/tag/1.2

**Comment by AnTiDoTxD** [comment]
Yup, I tested it, and it's fixed. Thanks bro, appreciate it!
